const { Router } = require('express');
const router = Router();
const subscriberRouter = require('./subscriberRouter');
const equipmentRouter = require('./equipmentRouter');
const addressRouter = require('./addressRouter');
const organizationRouter = require('./organizationRouter');
const installedEquipmentRouter = require('./installedEquipmentRouter');
const authRouter = require('./authRouter');
const activationRouter = require('./activationRouter');
const agreementRouter = require('./agreementRouter');  
router.use('/auth', authRouter);
router.use('/subscribers', subscriberRouter);
router.use('/equipment', equipmentRouter);
router.use('/addresses', addressRouter);
router.use('/organizations', organizationRouter);
router.use('/installed-equipment', installedEquipmentRouter);
router.use('/activate', activationRouter);
router.use('/agreements', agreementRouter);  
module.exports = router;